### ISSUE TITLE
esmlab.resample not found

### ISSUE THREAD

**Issue by matt-long** [NCAR/esmlab#125]
@brianpm has the following issue.
>I'm trying to use esmlab.resample(), but I’m getting the error that the module doesn’t have an attribute resample; same for esmlab.core.resample(). I can do `from esmlab import core` to get access to resample, but based on the `__init__` file, I’m guessing the intention is to have it available as esmlab.core.
>
>Anyway, I can work with it this way, but it wasn’t the behavior I expected.

@andersy005, can you help?

**Comment by brianpm** [comment]
Updating to esmlab.__version__ == '2019.4.27' appears to fix this issue; esmlab.resample() is there. (I'm still having trouble using it, but that would be a different issue 😅).

**Comment by matt-long** [comment]
Great (except for the new trouble)!

**Comment by andersy005** [comment]
@brianpm, glad you figured it out. Let me know if you encounter any other issues...
