### ISSUE TITLE
weighted_mean_da requires a list of dimensions (not just a string)

### ISSUE THREAD

**Issue by brianpm** [NCAR/esmlab#129]
The `weighted_mean_da` function documentation says the dim keyword should be "dimstr or sequence of str" but it does not seem to accept a plain string (which I what I think "dimstr" means). 

In the example below, when I just have `dim='lat'` it does not seem to do any calculation. When I switch to `dim=['lat']` it returns the expected reduced array.

PYTHON: 3.7.3 | packaged by conda-forge | (default, Mar 27 2019, 15:43:19) 
[Clang 4.0.1 (tags/RELEASE_401/final)]
Numpy: 1.16.3
xarray: 0.12.1
esmlab: 2019.4.27

```
import numpy as np
import xarray as xr
import esmlab
import sys

print(f"PYTHON: {sys.version}")
print(f"Numpy: {np.__version__}")
print(f"xarray: {xr.__version__}")
print(f"esmlab: {esmlab.__version__}")

ds = xr.open_dataset("/glade/scratch/brianpm/archive/cesm2_qpc6_aci_realaero/atm/hist/cesm2_qpc6_aci_realaero.cam.h0.0010-11.nc", decode_times=False)

wgt = ds['gw']
x = ds['T']

a1 = esmlab.statistics.weighted_mean_da(x, dim="lat", weights=wgt)  # expected: ([time], lev, lon)
print(a1)

a2 = esmlab.statistics.weighted_mean_da(x.squeeze(), dim="lat", weights=wgt)  # expected: (lev, lon)
print(a2)

a3 = esmlab.statistics.weighted_mean_da(x.squeeze(), dim=["lat"], weights=wgt)  # expected: (lev, lon)
print(a3)
```

**Comment by andersy005** [comment]
@brianpm, this is a bug indeed. Feel free to submit a pull request to fix this. If you don't have time, no worries, I'll handle it for you.

One solution would be to update `weighte_mean()` function by adding a check for the `dim` argument to make sure that if it's a string, it's passed to respective functions as a list of strings all the time:

```python
@esmlab_xr_set_options(arithmetic_join='exact', keep_attrs=True)
def weighted_mean(data, dim=None, weights=None):
    """ Compute weighted mean for xarray objects
    """
   
    if isinstance(dim, str):
        dim=[dim]
    if isinstance(data, xr.DataArray):
        return weighted_mean_da(data, dim, weights)
    elif isinstance(data, xr.Dataset):
        return data.apply(weighted_mean_da, dim=dim, weights=weights)

    else:
        raise ValueError('Data must be an xarray Dataset or DataArray')
```

Other functions in `statistics.py` such as `weighted_sum()`, `weighted_std()`, etc., will need to be patched as well .

By the way, this call:

```python

a1 = esmlab.statistics.weighted_mean_da(x, dim="lat", weights=wgt)
```

can be replaced by a dataset/dataarray agnostic call 

```python
a1 = esmlab.statistics.weighted_mean(x, dim="lat", weights=wgt)  
```

esmlab knows how to deal with either dataarray or dataset internally.

**Comment by brianpm** [comment]
Thanks, @andersy005 . I'm probably not going to have a chance to get a PR put together in the next week or more, so if anyone else wants to do it, I would encourage them to.
