### ISSUE TITLE
sel_time with optional methods

### ISSUE THREAD

**Issue by alperaltuntas** [NCAR/esmlab#149]
esmlab ```sel_time``` method can return only exact matches. But in absence of exact matches, it may be helpful to have a method option like xarray's ```sel``` method does (e.g., nearest). If this sounds okay, I can follow up with a PR where I add an optional method argument to ```sel_time```.

@andersy005 ?

**Comment by matt-long** [comment]
This seems like a relatively modest extension. I would say go for it.
