### ISSUE TITLE
Should esmlab functions return xarray objects for scalars?

### ISSUE THREAD

**Issue by mnlevy1981** [NCAR/esmlab#29]
* esmlab version:`2019.1.0
* xarray version: 0.11.2
* Python version: 3.6.7
* Operating System: macos 10.14.2

### Description

As discussed in #28, confusion can arise when a scalar value is returned as an `xarray` object... for example, taking the weighted average of an array where the weights and array have the same dimensions. In those cases, it might be preferable to return just the `values` attribute of the `xarray` object.

### What I Did

Had a conversation with @andersy005 that led to #28 and then thought more about what I expected to happen

**Comment by andersy005** [comment]
Resolved in https://github.com/NCAR/DIS/wiki/Meeting-Notes:-17-January-2019
