### ISSUE TITLE
Don't add NaNs for _FillValue

### ISSUE THREAD

**Issue by matt-long** [NCAR/esmlab#31]
`xarray` sets a `_FillValue = NaN` on writing to file if the `_FillValue` field in `encoding` is not set. I think this is undesirable; the preferred behavior would be for the absence of `_FillValue` to be preserved. 

This could be addressed in `get_original_attrs` by including something like the following.

```
    if '_FillValue' not in encoding:
        encoding['_FillValue'] = None
```

**Comment by andersy005** [comment]
This is now fixed. Thank you for the pointer, @matt-long!
