### ISSUE TITLE
statistics.weighted_mean does not work with single precision weights

### ISSUE THREAD

**Issue by mnlevy1981** [NCAR/esmlab#40]
* esmlab version: `2019.1.0`
* xarray version: `0.11.0`
* Python version: `2.7.14`
* Operating System: this is on `cheyenne`

### Description

I tried to compute the weighted average of a single-precision field, and it failed with the traceback

```
Traceback (most recent call last):
  File "./driver.py", line 45, in <module>
    AnalysisElement.do_analysis()
  File "/gpfs/fs1/work/mlevy/codes/marbl-diags/marbl_diags/analysis_elements_class.py", line 122, in do_analysis
    func(self, self._config_dict)
  File "/gpfs/fs1/work/mlevy/codes/marbl-diags/marbl_diags/analysis_ops.py", line 26, in plot_ann_climo
    _plot_climo(AnalysisElement, config_dict, valid_time_dims)
  File "/gpfs/fs1/work/mlevy/codes/marbl-diags/marbl_diags/analysis_ops.py", line 137, in _plot_climo
    fmean = esmlab.statistics.weighted_mean(field, TAREA).load().values
  File "/glade/work/mlevy/miniconda3/envs/NPL-conda/lib/python2.7/site-packages/esmlab/statistics.py", line 107, in weighted_mean
    weights = _apply_nan_mask(x, weights, avg_over_dims_v)
  File "/glade/work/mlevy/miniconda3/envs/NPL-conda/lib/python2.7/site-packages/esmlab/statistics.py", line 21, in _apply_nan_mask
    (weights / weights.sum(avg_over_dims_v)).sum(avg_over_dims_v), 1.0
  File "/glade/work/mlevy/miniconda3/envs/NPL-conda/lib/python2.7/site-packages/numpy/testing/nose_tools/utils.py", line 1396, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "/glade/work/mlevy/miniconda3/envs/NPL-conda/lib/python2.7/site-packages/numpy/testing/nose_tools/utils.py", line 779, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Not equal to tolerance rtol=1e-07, atol=0

(mismatch 100.0%)
 x: array(1., dtype=float32)
 y: array(1.)
```
### What I Did

More details are available in [NCAR/marbl-diags#10](https://github.com/marbl-ecosys/marbl-diags/issues/10), but I think the issue is in statistics.py:

```
def _apply_nan_mask(x, weights, avg_over_dims_v):
    weights = weights.where(x.notnull())
    np.testing.assert_allclose(
        (weights / weights.sum(avg_over_dims_v)).sum(avg_over_dims_v), 1.0
    )
return weights
```

The `1.0` argument to `np.testing.assert_allclose` needs to be the same type as `weights`. In my case, the weights are `TAREA` from `/glade/p/cesm/bgcwg/obgc_diag/data/obs_data/WOA2005/WOA05_ann_avg_gx1v6.nc`, which is a float (not a double).

**Comment by andersy005** [comment]
At a glance, this seems to be coming from `numpy.testing.assert_all_close()` function
- https://github.com/NCAR/esmlab/blob/master/esmlab/statistics.py#L20
- https://docs.scipy.org/doc/numpy-1.14.5/reference/generated/numpy.testing.assert_allclose.html

**Comment by mnlevy1981** [comment]
I think the answer is to use the `rtol` argument to `assert_allclose`, basing the tolerance off of `weights.dtype`. I'm not sure what the best option would be, but a good start is:

```
if weights.dtype == 'float32':
  rtol = 1e-6
else:
  rtol = 1e-12
weights = weights.where(x.notnull())
np.testing.assert_allclose((weights / weights.sum(avg_over_dims_v)).sum(avg_over_dims_v), 1.0, rtol=rtol)
```

That works for the WOA2005 dataset but I haven't tested it with the double precision datasets that worked previously... and maybe this should be more explicit about only accepting `float32` and `float64` data, raising an exception if anything else is encountered?

**Comment by andersy005** [comment]
@mnlevy1981, any update on this?

**Comment by mnlevy1981** [comment]
I think we have a couple of options:

1. Set `rtol` to `1e-6` regardless of `weights.dtype`
1. Set `rtol` to `1e-6` for `float32` but leave it at `1e-7` for all other types

I think going with (1) makes the most sense, though I'm open to other opinions. If we can come to a conclusion in this thread or at Thursday's meeting, I can put together a pull request.
