### ISSUE TITLE
groupby("time.month").mean("time") drops time_bound variable

### ISSUE THREAD

**Issue by alperaltuntas** [NCAR/esmlab#52]
### Description

```compute_mon_climatology``` function fails when run on multiple POP2 history files (glade/scratch/altuntas/archive/g.e20.GIAF.T62_g37.test_d2m.001/ocn/hist/g.e20.GIAF.T62_g37.test_d2m.001.pop.h.0001-*.nc)

As far as I can tell, this is because ```groupby("time.month").mean("time")``` call drops the ```"time_bound"``` variable when instantiating ```computed_dset```. This causes the function to fail at the following line within climatology.py
```
    computed_dset["month_bounds"] = (
        computed_dset[tb_name] - computed_dset[tb_name][0, 0]
    )
```
where ```tb_name=="time_bound"```

my environment = ncar_pylib_20190118 on cheyenne

### What I Did

```
# filePaths -> /glade/scratch/altuntas/archive/g.e20.GIAF.T62_g37.test_d2m.001/ocn/hist/g.e20.GIAF.T62_g37.test_d2m.001.pop.h.0001-*.nc
dset = xr.open_mfdataset(filePaths)
compute_mon_climatology(dset)
```

### Interactive Debugging (starting at climatology.py line 53):
```
(Pdb) 'time_bound' in dset
True
(Pdb) 'time_bound' in dset.drop(grid_vars)
True
(Pdb) 'time_bound' in dset.drop(grid_vars).groupby("time.month").mean("time")
False
(Pdb) 'time_bound' in dset.drop(grid_vars).groupby("time.month").mean("time").rename({"month": "time"})
False

```

**Comment by andersy005** [comment]
@alperaltuntas, which esmlab version are you using? For the time being, I recommend installing esmlab from source (master branch). There are some changes that are not available in the latest release.

**Comment by alperaltuntas** [comment]
Here is my esmlab version: esmlab==2019.1.0+27.g2b992eb

**Comment by andersy005** [comment]
The latest stable is version `2019.2.0` (https://pypi.org/project/esmlab/). You probably need to upgrade to this version: `pip install esmlab --upgrade`

**Comment by andersy005** [comment]
For latest features, bug fixes, I highly recommend installing from source for now. The next stable release is scheduled for next week.

**Comment by alperaltuntas** [comment]
I just switched to master, and it looks like it is still not working:

### traceback:
```
Traceback (most recent call last):
  File "/glade/work/altuntas/scripts/mncPy/mavg2.py", line 41, in <module>
    main()
  File "/glade/work/altuntas/scripts/mncPy/mavg2.py", line 37, in main
    compute_mon_climatology(dset)
  File "/gpfs/fs1/work/altuntas/ncar_pylib_20190118/lib/python3.6/site-packages/esmlab/climatology.py", line 75, in compute_mon_climatology
    computed_dset[tb_name] - computed_dset[tb_name][0, 0]
  File "/gpfs/fs1/work/altuntas/ncar_pylib_20190118/lib/python3.6/site-packages/xarray/core/dataset.py", line 970, in __getitem__
    return self._construct_dataarray(key)
  File "/gpfs/fs1/work/altuntas/ncar_pylib_20190118/lib/python3.6/site-packages/xarray/core/dataset.py", line 899, in _construct_dataarray
    self._variables, name, self._level_coords, self.dims)
  File "/gpfs/fs1/work/altuntas/ncar_pylib_20190118/lib/python3.6/site-packages/xarray/core/dataset.py", line 74, in _get_virtual_variable
    ref_var = variables[ref_name]
KeyError: 'time_bound'
```
### interactive debugging

```
(Pdb) 'time_bound' in dset
True
(Pdb) 'time_bound' in dset.drop(static_variables)
True
(Pdb) 'time_bound' in dset.drop(static_variables).groupby(time_dot_month).mean(time_coord_name)
False

```

**Comment by andersy005** [comment]
Okie dokie.. let me look into it. I will get back to you

**Comment by andersy005** [comment]
@alperaltuntas, I can confirm that this is a bug. 

Ccing @matt-long

**Comment by andersy005** [comment]
Would you be interested in submitting a PR to fix it? @alperaltuntas

**Comment by alperaltuntas** [comment]
> Would you be interested in submitting a PR to fix it? @alperaltuntas

Sure, I'll work on this.

**Comment by matt-long** [comment]
@alperaltuntas, @andersy005: I was not able to reproduce this error.

Here's what I did.
```python
from glob import glob
import xarray as xr
import esmlab

files = sorted(glob('/glade/scratch/altuntas/archive/g.e20.GIAF.T62_g37.test_d2m.001/ocn/hist/g.e20.GIAF.T62_g37.test_d2m.001.pop.h.0001-*.nc'))

ds = xr.open_mfdataset(files, decode_times=False, decode_coords=False)
ds_monclim = esmlab.climatology.compute_mon_climatology(ds)
```
Works fine.

version = 'v2019.1.0+42.g4c2339c'

So that's a bit of mystery. @alperaltuntas, you have confirmed that you are still getting the error?

I think it's important to note, however, independent of this error, that the function is not doing the right thing for these data. Since you are averaging 5-day data to monthly bounds, we should really consider the portion of the `time_bound` window that overlaps with each month and compute a weighted mean of the values, apportioning the weights for data points overlapping 2 months appropriately.  This is a limitation of the current framework and might be characterized as a bug.

**Comment by alperaltuntas** [comment]
Thanks, @matt-long. Apparently, adding ```decode_times=False``` argument in open_mfdataset call fixes the issue with ```time_bound```.
