### ISSUE TITLE
_get_weights_and_dims should accept tuple dim argument

### ISSUE THREAD

**Issue by matt-long** [NCAR/esmlab#86]
This line
https://github.com/NCAR/esmlab/blob/878b80c3477a6c9fd990148ada299b51217d3020/esmlab/statistics.py#L39
should check for iterable, not just list.

**Comment by jukent** [comment]
Thanks Matt I will look at this on Monday! Focusing on my MS thesis this weekend.

**Comment by andersy005** [comment]
Fixed in #97
