### ISSUE TITLE
compute_ann_mean does not preserve time:calendar

### ISSUE THREAD

**Issue by klindsay28** [NCAR/esmlab#92]
I'm calling `ds_ann = compute_ann_mean(ds)` on an xarry Dataset where `ds.time.attrs` includes 'calendar' and am finding that `ds_ann.time.attrs` does not include 'calendar'.

The python code in the following file, which has a .txt suffix to enable me to attach it, exhibits the problem:
[esmlab_compute_ann_mean_calendar.py.txt](https://github.com/NCAR/esmlab/files/2954226/esmlab_compute_ann_mean_calendar.py.txt)

The python creates an example Dataset object, `ds`, in which `ds.time.attrrs` includes 'calendar',  calls `ds_ann = compute_ann_mean(ds)`, and writes out `ds.time.attrs` and `ds_ann.time.attrs`.

Using the trunk of esmlab, I get the output:

> OrderedDict([('units', 'days since 0001-01-01'), ('calendar', 'noleap'), ('bounds', 'time_bounds')])
OrderedDict([('long_name', 'time'), ('units', 'days since 0001-01-01 00:00:00'), ('bounds', 'time_bounds')])

I expect the 2nd line to include 'calendar', like the first line does, but it doesn't.

My reading of the code leads me to expect that this should be happening, but it is not working for me. I don't understand the code well enough to understand why it isn't working.

(It also looks like `compute_ann_mean` has added 'long_name` to `ds_ann.time.attrs`, which I don't expect it to do.)

**Comment by andersy005** [comment]
Fixed in #98, #100
